import { DRZAVE, type Drzava } from "@/types/database";

export const GRADOVI_PO_DRZAVI: Record<Drzava, readonly string[]> = {
  "Bosna i Hercegovina": [
    "Sarajevo",
    "Banja Luka",
    "Tuzla",
    "Zenica",
    "Mostar",
    "Bijeljina",
    "Brčko",
    "Prijedor",
    "Doboj",
    "Cazin",
    "Zvornik",
    "Živinice",
    "Gradačac",
    "Gračanica",
    "Travnik",
    "Bihać",
    "Lukavac",
    "Tešanj",
    "Konjic",
    "Visoko",
    "Goražde",
    "Bosanska Krupa",
    "Velika Kladuša",
    "Srebrenik",
    "Bugojno",
    "Gradiška",
    "Zavidovići",
    "Sanski Most",
    "Mrkonjić Grad",
    "Kakanj",
    "Vitez",
    "Žepče",
    "Široki Brijeg",
    "Čapljina",
    "Stolac",
    "Trebinje",
    "Foča",
    "Modriča",
    "Derventa",
    "Prnjavor",
    "Laktaši",
    "Teslić",
    "Kotor Varoš",
    "Čelinac",
    "Srbac",
    "Kalesija",
    "Maglaj",
    "Odžak",
    "Orašje",
    "Ljubuški",
    "Posušje",
    "Grude",
    "Jajce",
    "Novi Travnik",
    "Kiseljak",
    "Busovača",
    "Fojnica",
    "Kreševo",
    "Olovo",
    "Vareš",
    "Breza",
    "Hadžići",
    "Ilijaš",
    "Ilidža",
    "Pale",
    "Sokolac",
    "Rogatica",
    "Višegrad",
    "Rudo",
    "Nevesinje",
    "Bileća",
    "Gacko",
    "Ljubinje",
    "Srebrenica",
    "Bratunac",
    "Vlasenica",
    "Milići",
    "Šekovići",
    "Kladanj",
    "Banovići",
    "Čelić",
    "Sapna",
    "Teočak",
    "Ugljevik",
    "Lopare",
    "Šamac",
    "Donji Vakuf",
    "Gornji Vakuf-Uskoplje",
    "Jablanica",
    "Prozor-Rama",
    "Glamoč",
    "Kupres",
    "Tomislavgrad",
    "Livno",
    "Drvar",
    "Bosanski Petrovac",
    "Ključ",
    "Novi Grad",
    "Kostajnica",
    "Krupa na Uni",
    "Oštra Luka",
    "Ribnik",
    "Šipovo",
    "Jezero",
    "Istočno Sarajevo",
    "Han Pijesak",
  ],
  Srbija: [
    "Beograd",
    "Novi Sad",
    "Niš",
    "Kragujevac",
    "Subotica",
    "Zrenjanin",
    "Pančevo",
    "Čačak",
    "Kraljevo",
    "Novi Pazar",
    "Leskovac",
    "Užice",
    "Vranje",
    "Šabac",
    "Smederevo",
    "Valjevo",
    "Kruševac",
    "Kikinda",
    "Sombor",
    "Požarevac",
    "Pirot",
    "Zaječar",
    "Sremska Mitrovica",
    "Jagodina",
    "Vršac",
    "Bor",
    "Prokuplje",
    "Loznica",
    "Ruma",
    "Inđija",
    "Stara Pazova",
    "Bačka Palanka",
    "Vrbas",
    "Senta",
    "Apatin",
    "Kula",
    "Bečej",
    "Temerin",
    "Ćuprija",
    "Paraćin",
    "Aleksinac",
    "Negotin",
    "Knjaževac",
    "Svilajnac",
    "Despotovac",
    "Velika Plana",
    "Smederevska Palanka",
    "Aranđelovac",
    "Topola",
    "Gornji Milanovac",
    "Ivanjica",
    "Arilje",
    "Požega",
    "Bajina Bašta",
    "Kosjerić",
    "Priboj",
    "Prijepolje",
    "Nova Varoš",
    "Sjenica",
    "Tutin",
    "Raška",
    "Vrnjačka Banja",
    "Trstenik",
    "Brus",
    "Blace",
    "Kuršumlija",
    "Žitorađa",
    "Doljevac",
    "Merošina",
    "Gadžin Han",
    "Bela Palanka",
    "Babušnica",
    "Dimitrovgrad",
    "Surdulica",
    "Vladičin Han",
    "Bujanovac",
    "Preševo",
    "Bosilegrad",
    "Trgovište",
    "Vlasotince",
    "Crna Trava",
    "Lebane",
    "Bojnik",
    "Medveđa",
    "Lapovo",
    "Rača",
    "Batočina",
    "Knić",
    "Ub",
    "Lajkovac",
    "Mionica",
    "Ljig",
    "Osečina",
    "Krupanj",
    "Mali Zvornik",
    "Ljubovija",
    "Bogatić",
    "Vladimirci",
    "Koceljeva",
    "Lazarevac",
    "Obrenovac",
    "Mladenovac",
    "Sopot",
    "Barajevo",
    "Grocka",
    "Pećinci",
    "Irig",
    "Šid",
    "Ada",
    "Kanjiža",
    "Mali Iđoš",
    "Bačka Topola",
    "Žabalj",
    "Titel",
    "Srbobran",
    "Bač",
    "Beočin",
    "Sremski Karlovci",
    "Opovo",
    "Kovačica",
    "Kovin",
    "Plandište",
    "Bela Crkva",
    "Alibunar",
    "Nova Crnja",
    "Žitište",
    "Sečanj",
    "Novi Kneževac",
    "Čoka",
    "Odžaci",
  ],
  Hrvatska: [
    "Zagreb",
    "Split",
    "Rijeka",
    "Osijek",
    "Zadar",
    "Pula",
    "Slavonski Brod",
    "Karlovac",
    "Varaždin",
    "Šibenik",
    "Dubrovnik",
    "Bjelovar",
    "Sisak",
    "Vinkovci",
    "Vukovar",
    "Čakovec",
    "Velika Gorica",
    "Koprivnica",
    "Đakovo",
    "Požega",
    "Kutina",
    "Samobor",
    "Virovitica",
    "Križevci",
    "Gospić",
    "Krapina",
    "Metković",
    "Nova Gradiška",
    "Daruvar",
    "Ogulin",
    "Sinj",
    "Knin",
    "Vrbovec",
    "Petrinja",
    "Zaprešić",
    "Dugo Selo",
    "Sveti Ivan Zelina",
    "Jastrebarsko",
    "Ivanić-Grad",
    "Beli Manastir",
    "Našice",
    "Valpovo",
    "Belišće",
    "Županja",
    "Đurđevac",
    "Ludbreg",
    "Novska",
    "Garešnica",
    "Grubišno Polje",
    "Pakrac",
    "Lipik",
    "Slatina",
    "Orahovica",
    "Pleternica",
    "Pazin",
    "Rovinj",
    "Poreč",
    "Umag",
    "Buzet",
    "Labin",
    "Buje",
    "Vodnjan",
    "Crikvenica",
    "Opatija",
    "Kastav",
    "Kraljevica",
    "Bakar",
    "Cres",
    "Mali Lošinj",
    "Krk",
    "Rab",
    "Senj",
    "Otočac",
    "Novalja",
    "Pag",
    "Biograd na Moru",
    "Benkovac",
    "Obrovac",
    "Nin",
    "Vodice",
    "Drniš",
    "Skradin",
    "Trogir",
    "Kaštela",
    "Solin",
    "Omiš",
    "Makarska",
    "Imotski",
    "Vrgorac",
    "Hvar",
    "Stari Grad",
    "Vis",
    "Korčula",
    "Ploče",
    "Opuzen",
    "Trilj",
    "Supetar",
    "Zabok",
    "Oroslavje",
    "Pregrada",
    "Klanjec",
    "Zlatar",
    "Mursko Središće",
    "Prelog",
    "Ivanec",
    "Lepoglava",
    "Novi Marof",
    "Varaždinske Toplice",
  ],
  "Crna Gora": [
    "Podgorica",
    "Nikšić",
    "Pljevlja",
    "Bijelo Polje",
    "Cetinje",
    "Bar",
    "Herceg Novi",
    "Berane",
    "Budva",
    "Ulcinj",
    "Tivat",
    "Rožaje",
    "Kotor",
    "Danilovgrad",
    "Mojkovac",
    "Plav",
    "Kolašin",
    "Žabljak",
    "Andrijevica",
    "Plužine",
    "Šavnik",
    "Petnjica",
    "Gusinje",
    "Tuzi",
    "Zeta",
  ],
};

export function gradoviZaDrzavu(drzava: Drzava): string[] {
  return [...(GRADOVI_PO_DRZAVI[drzava] ?? [])].sort((a, b) =>
    a.localeCompare(b, "sr"),
  );
}

export function gradoviZaDrzave(drzave: Drzava[]): string[] {
  const set = new Set<string>();
  for (const d of drzave) {
    for (const g of GRADOVI_PO_DRZAVI[d] ?? []) {
      set.add(g);
    }
  }
  return [...set].sort((a, b) => a.localeCompare(b, "sr"));
}

export function drzavaZaGrad(grad: string): Drzava | null {
  for (const drzava of DRZAVE) {
    if (GRADOVI_PO_DRZAVI[drzava].includes(grad)) return drzava;
  }
  return null;
}

export { DRZAVE };
